export const LANGUAGES = [
  { code: "en", name: "English", native: "English", letter: "E", speech: "en-IN" },
  { code: "hi", name: "Hindi", native: "हिन्दी", letter: "ह", speech: "hi-IN" },
  { code: "bn", name: "Bengali", native: "বাংলা", letter: "ব", speech: "bn-IN" },
  { code: "te", name: "Telugu", native: "తెలుగు", letter: "త", speech: "te-IN" },
  { code: "mr", name: "Marathi", native: "मराठी", letter: "म", speech: "mr-IN" },
  { code: "ta", name: "Tamil", native: "தமிழ்", letter: "த", speech: "ta-IN" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી", letter: "ગ", speech: "gu-IN" },
  { code: "ur", name: "Urdu", native: "اردو", letter: "ا", speech: "ur-IN" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", letter: "ಕ", speech: "kn-IN" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ", letter: "ଓ", speech: "or-IN" },
  { code: "ml", name: "Malayalam", native: "മലയാളം", letter: "മ", speech: "ml-IN" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ", letter: "ਪ", speech: "pa-IN" },
  { code: "as", name: "Assamese", native: "অসমীয়া", letter: "অ", speech: "as-IN" },
  { code: "mai", name: "Maithili", native: "मैथिली", letter: "म", speech: "hi-IN" },
  { code: "sat", name: "Santali", native: "ᱥᱟᱱᱛᱟᱲᱤ", letter: "ᱥ", speech: "hi-IN" },
  { code: "ks", name: "Kashmiri", native: "کٲشُر", letter: "ک", speech: "ur-IN" },
  { code: "ne", name: "Nepali", native: "नेपाली", letter: "न", speech: "ne-IN" },
  { code: "kok", name: "Konkani", native: "कोंकणी", letter: "क", speech: "mr-IN" },
  { code: "sd", name: "Sindhi", native: "سنڌي", letter: "س", speech: "ur-IN" },
  { code: "doi", name: "Dogri", native: "डोगरी", letter: "ड", speech: "hi-IN" },
  { code: "mni", name: "Manipuri", native: "ꯃꯤꯇꯩꯂꯣꯟ", letter: "ꯃ", speech: "hi-IN" },
  { code: "brx", name: "Bodo", native: "बड़ो", letter: "ब", speech: "hi-IN" },
  { code: "sa", name: "Sanskrit", native: "संस्कृतम्", letter: "स", speech: "hi-IN" },
];
